### ISSUE TITLE
pip install failed

### ISSUE THREAD

**Issue by silvercondor** [eosmoto/eosiopy#12]
error log

C:\Scripts> pip install eosiopy
Collecting eosiopy
  Downloading https://files.pythonhosted.org/packages/d1/a2/128733b064a6e3f0196509457f6bbb73a9a05701826a57bb60ca993912e6/eosiopy-0.1.4.tar.gz (53kB)
    100% |████████████████████████████████| 61kB 2.6MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\lambd\AppData\Local\Temp\pip-install-l7_vh_s9\eosiopy\setup.py", line 11, in <module>
        long_description = f.read().strip()
      File "C:\Users\lambd\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 234: character maps to <undefined>

**Comment by eosmoto** [comment]
This is a question of your system coding
