### ISSUE TITLE
invalid ELF header with docker

### ISSUE THREAD

**Issue by avral** [eosmoto/eosiopy#5]
```
Traceback (most recent call last):
  File "main.py", line 69, in <module>
    eos_issue(eos_receiver, amount)
  File "/app/eos.py", line 32, in eos_issue
    eosiop_arams = EosioParams(raw.params_actions_list, ISSUER_WIF)
  File "/usr/local/lib/python3.6/site-packages/eosiopy/eosioparams.py", line 30, in __init__
    self.sign(wif)
  File "/usr/local/lib/python3.6/site-packages/eosiopy/eosioparams.py", line 43, in sign
    signatures.append(sign(wif, self.params["packed_trx"].get_digest_signature()))
  File "/usr/local/lib/python3.6/site-packages/eosiopy/sign.py", line 33, in sign
    libuecc = ll(libuecc)
  File "/usr/local/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.6/site-packages/eosiopy/uECC.so: invalid ELF header
```

python docker image: python:3.6.5

without docker all works fine

**Comment by eosmoto** [comment]
I releases the new versions  just now.[v0.1.2](https://github.com/eosmoto/eosiopy/releases/tag/v0.1.2)
